config/routes.rb
Rails.application.routes.draw do

  #get 'microposts/index'

  #get 'microposts/show'

  #get 'users/index'

  #get 'users/show'
  
  #get 'users/edit'


  root 'static_pages#home'
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:index, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">  
  <small>
    The <a href="https://railstutorial.jp/">Instagram sample app</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Upload Pictures", microposts_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Instagram sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "ホーム", root_path %></li>
            <% if user_signed_in? %>
             <li><%= link_to "ユーザー一覧", users_path %></li>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 アカウント設定 <b class="caret"></b>
               </a>
               <ul class="dropdown-menu">
                 <li><%= link_to "ユーザープロフィール", current_user %></li>
                 <li><%= link_to "ユーザー情報詳細設定", edit_user_registration_path(current_user) %></li>
                 <li class="divider"></li>
                 <li>
                   <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                 </li>
               </ul>
             </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
 <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
 </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
  </head>
  
  

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
     <%= yield %>
     <%= render 'layouts/footer' %>
    </div>
  </body>
</html>